### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by ghost** [ofats/any_invocable#1]
Nice early preview,

What's the license?

**Comment by alexhultman** [comment]
So... are we allowed to use the code?

**Comment by ghost** [comment]
I'm still interested. Any hint on license?

**Comment by cor3ntin** [comment]
I'm also interested, thanks!

**Comment by ghost** [comment]
This feature was dropped from C++20 so it would be nice to have a license. Currently nobody may use this code without breaking copyright laws

**Comment by ofats** [comment]
Hello, thank you for your interest.
Will add a license shortly, sorry for such a huge delay.

**Comment by Ramil-ufa** [comment]
Let's
